name: Build FastAPI App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t flaskapp:latest ./mypythonapp

    # In a real-world scenario, you would add steps here to push to a Docker registry
    # and then deploy to your cloud provider (e.g., AWS ECR, Google Container Registry, Azure Container Registry)
    # For this exercise, we are focusing on the build step.
